const mongoose = require("mongoose");
const path = require("path");
require("dotenv").config();
const ShopItem = require("../models/ShopItem");

const items = [
    {
        _id: new mongoose.Types.ObjectId("69ebd6a439c603d2759d7d21"),
        name: "Cake",
        description: "A sweet treat that gives your pet a burst of energy.",
        category: "food",
        itemType: "consumable",
        equipSlot: "none",
        cost: 25,
        effectType: "hunger",
        effectValue: 30,
        xpValue: 10,
        strengthValue: 0,
        speedValue: 1,
        defenseValue: 0,
        petSpecies: "none",
        unlockLevel: 2,
        isActive: true,
        imageKey: "/assets/items/consumables/hunger/Cake.png",
        animationType: "feed",
    },
    {
        _id: new mongoose.Types.ObjectId("69ebd6b939c603d2759d7d23"),
        name: "Storybook",
        description: "A fun story that keeps your pet entertained and happy.",
        category: "toy",
        itemType: "consumable",
        equipSlot: "none",
        cost: 18,
        effectType: "happiness",
        effectValue: 25,
        xpValue: 5,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "none",
        unlockLevel: 1,
        isActive: true,
        imageKey: "/assets/items/consumables/happiness/MythicalBook.png",
        animationType: "book",
    },
    {
        _id: new mongoose.Types.ObjectId("69ebd6c839c603d2759d7d25"),
        name: "Pet Shampoo",
        description: "A bubbly wash that leaves your pet fresh and sparkling clean.",
        category: "care",
        itemType: "consumable",
        equipSlot: "none",
        cost: 18,
        effectType: "cleanliness",
        effectValue: 25,
        xpValue: 5,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "none",
        unlockLevel: 1,
        isActive: true,
        imageKey: "/assets/items/consumables/cleanliness/LightMpPotion.png",
        animationType: "brush",
    },
    {
        _id: new mongoose.Types.ObjectId("69ebd7d439c603d2759d7d27"),
        name: "Bow",
        description: "A cute decorative bow.",
        category: "accessory",
        itemType: "cosmetic",
        equipSlot: "accessory",
        cost: 50,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "none",
        unlockLevel: 1,
        isActive: true,
        imageKey: "/assets/items/cosmetics/hats/bow.png",
        animationType: "none",
    },
    {
        _id: new mongoose.Types.ObjectId("69f275d2ab858f7ce4fbabe2"),
        name: "Plains",
        description: "A peaceful plains scene for your pet.",
        category: "background",
        itemType: "cosmetic",
        equipSlot: "background",
        cost: 50,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "none",
        unlockLevel: 1,
        isActive: true,
        imageKey: "/assets/items/cosmetics/backgrounds/GrassBG.png",
        animationType: "none",
    },
    {
        _id: new mongoose.Types.ObjectId("69f7f79c5ba7fc978afd24b2"),
        name: "Pengu",
        description: "A cheerful penguin companion.",
        category: "pet",
        itemType: "pet",
        equipSlot: "none",
        cost: 200,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "pengu",
        unlockLevel: 1,
        isActive: true,
        imageKey: "/assets/pets/pengu.png",
        animationType: "none",
    },
    {
        _id: new mongoose.Types.ObjectId("69fd75600173593b90cf515f"),
        name: "Wolfy",
        description: "A loyal and energetic companion.",
        category: "pet",
        itemType: "pet",
        equipSlot: "none",
        cost: 200,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "wolfy",
        unlockLevel: 1,
        isActive: true,
        imageKey: "/assets/pets/wolfy.png",
        animationType: "none",
    },
    {
        _id: new mongoose.Types.ObjectId("69fd75700173593b90cf5161"),
        name: "Snazake",
        description: "A sleek and mysterious serpent.",
        category: "pet",
        itemType: "pet",
        equipSlot: "none",
        cost: 200,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "snazake",
        unlockLevel: 1,
        isActive: true,
        imageKey: "/assets/pets/snazake.png",
        animationType: "none",
    },
    {
        _id: new mongoose.Types.ObjectId("6a00166ef289273cb7acb73e"),
        name: "Green Bacon",
        description: "A questionable snack... but pets seem to love it.",
        category: "food",
        itemType: "consumable",
        equipSlot: "none",
        cost: 15,
        effectType: "hunger",
        effectValue: 20,
        xpValue: 5,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "none",
        unlockLevel: 1,
        isActive: true,
        imageKey: "/assets/items/consumables/hunger/ZombieJerky.png",
        animationType: "feed",
    },
    {
        name: "Slime",
        description: "A wobbly, gooey companion that loves to bounce around.",
        category: "pet",
        itemType: "pet",
        equipSlot: "none",
        cost: 150,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "slimepet",
        unlockLevel: 3,
        isActive: true,
        imageKey: "/assets/pets/slimepet.png",
        animationType: "none",
    },
    {
        name: "Prickling",
        description: "A small spiky critter with a surprisingly sweet personality.",
        category: "pet",
        itemType: "pet",
        equipSlot: "none",
        cost: 175,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "prickling",
        unlockLevel: 5,
        isActive: true,
        imageKey: "/assets/pets/prickling.png",
        animationType: "none",
    },
    {
        name: "Dust Bunny",
        description: "A fluffy little cloud of mischief that floats wherever it pleases.",
        category: "pet",
        itemType: "pet",
        equipSlot: "none",
        cost: 200,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "dustbunny",
        unlockLevel: 6,
        isActive: true,
        imageKey: "/assets/pets/dustbunny.png",
        animationType: "none",
    },
    {
        name: "Baby Dragon",
        description: "A tiny dragon with big dreams",
        category: "pet",
        itemType: "pet",
        equipSlot: "none",
        cost: 400,
        effectType: "none",
        effectValue: 0,
        xpValue: 0,
        strengthValue: 0,
        speedValue: 0,
        defenseValue: 0,
        petSpecies: "babydragon",
        unlockLevel: 10,
        isActive: true,
        imageKey: "/assets/pets/babydragon.png",
        animationType: "none",
    },
];

mongoose.connect(process.env.MONGO_URI).then(async () => {
    await ShopItem.bulkWrite(
        items.map(item => ({
            updateOne: {
                filter: item._id ? { _id: item._id } : { name: item.name },
                update: { $set: item },
                upsert: true,
            },
        }))
    );
    console.log("Shop items seeded successfully.");
    mongoose.disconnect();
}).catch(err => {
    console.error("Seed failed:", err);
    process.exit(1);
});
